
set(CMAKE_SYSTEM_NAME Windows-GNU)
set(CMAKE_SYSTEM_PROCESSOR "i686")

set(CLANG TRUE CACHE INTERNAL "")
set(MINGW TRUE CACHE INTERNAL "")
set(WIN32 TRUE CACHE INTERNAL "")

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang.exe")
set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/clang++.exe")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/bin/llvm-ar.exe" CACHE INTERNAL "")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/bin/llvm-ranlib.exe" CACHE INTERNAL "")
set(CMAKE_RC_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/windres.exe" CACHE INTERNAL "")

set(CMAKE_C_FLAGS_INIT "-target i686-w64-mingw32")
set(CMAKE_CXX_FLAGS_INIT "-target i686-w64-mingw32")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Wno-unused-command-line-argument -rtlib=compiler-rt -lgcc -lgcc_s")

set(CMAKE_RC_COMPILE_OBJECT
    "<CMAKE_RC_COMPILER> <FLAGS> -O coff <DEFINES> -i <SOURCE> -o <OBJECT>"
    CACHE INTERNAL "")

set(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
    CACHE INTERNAL "")

set(CMAKE_USER_MAKE_RULES_OVERRIDE "${CMAKE_CURRENT_LIST_DIR}/toolchain-override.cmake")
include("${CMAKE_USER_MAKE_RULES_OVERRIDE}")
